name: Test Package

on: [push]

env:
  PROVIDER_URL: https://eth-rpc.gateway.pokt.network
  ARBITRUM_PROVIDER_URL: https://1rpc.io/arb
  OPTIMISM_PROVIDER_URL: https://endpoints.omniatech.io/v1/op/mainnet/public
  MAINNET_PROVIDER_URL: https://eth.llamarpc.com
  ZEROX_API_KEY: ${{ secrets.ZEROX_API_KEY }}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint:ci
      - run: bun run test
